# Generated by Django 5.2.7 on 2025-10-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avio_codigo', models.CharField(max_length=30, unique=True)),
                ('avio_capacidad', models.CharField(max_length=30)),
            ],
        ),
    ]
