# Generated by Django 5.2 on 2025-11-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avion',
            old_name='avio_capacidad',
            new_name='avion_capacidad',
        ),
        migrations.RenameField(
            model_name='avion',
            old_name='avio_codigo',
            new_name='avion_codigo',
        ),
    ]
