# Generated by Django 5.2.7 on 2025-10-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasa_nombre', models.CharField(max_length=30)),
                ('pasa_email', models.CharField(blank=True, max_length=50, null=True)),
                ('pasa_telefono', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
