# Generated by Django 5.2.7 on 2025-10-18 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aviones', '0001_initial'),
        ('pasajeros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuel_origen', models.CharField(max_length=30)),
                ('vuel_destino', models.CharField(max_length=30)),
                ('vuel_fecha', models.DateField()),
                ('avio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviones.avion')),
            ],
        ),
        migrations.CreateModel(
            name='VueloXPasajeros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajeros.pasajero')),
                ('vuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelos.vuelo')),
            ],
        ),
    ]
